"""update User table

Revision ID: eb9b67522439
Revises: 9531c2cbd3ba
Create Date: 2025-03-23 00:43:16.614305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9b67522439'
down_revision: Union[str, None] = '9531c2cbd3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('proxy_type', sa.String(), nullable=False),
    sa.Column('proxy_host', sa.String(), nullable=False),
    sa.Column('proxy_port', sa.BigInteger(), nullable=False),
    sa.Column('proxy_login', sa.String(), nullable=True),
    sa.Column('proxy_password', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_settings_id'), 'proxy_settings', ['id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_proxy_settings_id'), table_name='proxy_settings')
    op.drop_table('proxy_settings')
    # ### end Alembic commands ###
